2021-08-06

diff --git a/.git_template/hooks/pre-push b/.git_template/hooks/pre-push
--- a/.git_template/hooks/pre-push
+++ b/.git_template/hooks/pre-push
@@ -1,13 +1,12 @@
 #!/bin/bash
 
-echo '[warn] push to remote, continue? [y/N]'
-
-exec < /dev/tty
-read answer
-
-case $answer in
-    'y' | 'yes') echo '[info] OK. push start.';;
-    * ) echo '[error] push failed.';exit 1;;
-esac
-exit 0
-
+#echo '[warn] push to remote, continue? [y/N]'
+#
+#exec < /dev/tty
+#read answer
+#
+#case $answer in
+#    'y' | 'yes') echo '[info] OK. push start.';;
+#    * ) echo '[error] push failed.';exit 1;;
+#esac
+#exit 0
